### ISSUE TITLE
Race conditions in threading library

### ISSUE THREAD

**Issue by erlingrj** [pretis/flexpret#56]
Writes to the `tmodes` register is generally unsafe because it has the mode of ALL threads. We need to rethink if we ever can safely write to that register

**Comment by lsk567** [comment]
It is also inefficient since a thread needs to compute a new value by doing all the masking and bit-level operations first before writing to `tmodes`. Because of this, it is not possible to atomically write to `tmodes`, hence not possible for a thread to put itself to sleep.

A possible solution is to have eight `tmode` CSRs, one for each thread, and a thread can write to one of them atomically without worrying about other threads.
